# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "local"

[[repos.hooks]]
id = "prettier"
name = "prettier (format whole repo)"
entry = "bunx prettier -w ."
language = "system"
pass_filenames = false
always_run = true
