import type { Theme } from "@fluentui/react-components";

const LIGHT = {
  colorNeutralBackground1: "#ffffff",
  colorNeutralBackground1Hover: "#fafafa",
  colorNeutralBackground1Pressed: "#f0f0f0",
  colorNeutralBackground1Selected: "#f0f0f0",
  colorNeutralBackground2: "#ffffff",
  colorNeutralBackground2Hover: "#fafafa",
  colorNeutralBackground2Pressed: "#f0f0f0",
  colorNeutralBackground2Selected: "#f0f0f0",
  colorNeutralBackground3: "#f5f5f5",
  colorNeutralBackground3Hover: "#eaeaea",
  colorNeutralBackground3Pressed: "#dedede",
  colorNeutralBackground3Selected: "#eaeaea",
  colorNeutralBackground4: "#e0e0e0",
  colorNeutralBackground4Hover: "#d5d5d5",
  colorNeutralBackground4Pressed: "#cacaca",
  colorNeutralBackground4Selected: "#d5d5d5",
  colorNeutralBackground5: "#cccccc",
  colorNeutralBackground5Hover: "#c0c0c0",
  colorNeutralBackground5Pressed: "#b5b5b5",
  colorNeutralBackground5Selected: "#c0c0c0",
  colorNeutralBackground6: "#b8b8b8",
  colorNeutralBackground7: "#000000",
  colorNeutralForeground1: "#000000",
  colorNeutralForeground2: "#333333",
  colorNeutralForeground2Hover: "#000000",
  colorNeutralForeground2Pressed: "#000000",
  colorNeutralForeground3: "#555555",
  colorNeutralForeground4: "#777777",
  colorNeutralStroke1: "#999999",
  colorNeutralStroke2: "#d0d0d0",
  colorNeutralStroke3: "#e0e0e0",
  colorNeutralStrokeAccessible: "#000000",
  colorNeutralForegroundOnBrand: "#ffffff",
};

const DARK = {
  colorNeutralBackground1: "#000000",
  colorNeutralBackground1Hover: "#0a0a0a",
  colorNeutralBackground1Pressed: "#141414",
  colorNeutralBackground1Selected: "#141414",
  colorNeutralBackground2: "#0a0a0a",
  colorNeutralBackground2Hover: "#141414",
  colorNeutralBackground2Pressed: "#1e1e1e",
  colorNeutralBackground2Selected: "#141414",
  colorNeutralBackground3: "#141414",
  colorNeutralBackground3Hover: "#1e1e1e",
  colorNeutralBackground3Pressed: "#282828",
  colorNeutralBackground3Selected: "#1e1e1e",
  colorNeutralBackground4: "#1e1e1e",
  colorNeutralBackground4Hover: "#282828",
  colorNeutralBackground4Pressed: "#323232",
  colorNeutralBackground4Selected: "#282828",
  colorNeutralBackground5: "#282828",
  colorNeutralBackground5Hover: "#323232",
  colorNeutralBackground5Pressed: "#3c3c3c",
  colorNeutralBackground5Selected: "#323232",
  colorNeutralBackground6: "#323232",
  colorNeutralBackground7: "#ffffff",
  colorNeutralForeground1: "#ffffff",
  colorNeutralForeground2: "#cccccc",
  colorNeutralForeground2Hover: "#ffffff",
  colorNeutralForeground2Pressed: "#ffffff",
  colorNeutralForeground3: "#888888",
  colorNeutralForeground4: "#666666",
  colorNeutralStroke1: "#333333",
  colorNeutralStroke2: "#222222",
  colorNeutralStroke3: "#1a1a1a",
  colorNeutralStrokeAccessible: "#ffffff",
  colorNeutralForegroundOnBrand: "#000000",
};

const TOKENS = {
  borderRadiusLarge: "10px",
  borderRadiusMedium: "8px",
  borderRadiusXLarge: "12px",
  borderRadius2XLarge: "14px",
  shadow2: "none",
  shadow4: "none",
  shadow8: "none",
  shadow16: "none",
  shadow28: "none",
  shadow64: "none",
  shadow2Brand: "none",
  shadow4Brand: "none",
  shadow8Brand: "none",
  shadow16Brand: "none",
  shadow28Brand: "none",
  shadow64Brand: "none",
};

export function patchTheme(theme: Theme, dark: boolean): Theme {
  const colors = dark ? DARK : LIGHT;
  return {
    ...theme,
    ...TOKENS,
    ...colors,
  };
}
